name: cooperativa_final
description: "App tipo InDriver para motorizados y clientes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  image_picker: ^1.1.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^13.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Configuración necesaria para que el logo se genere correctamente
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/fondoCM.jpg
    - assets/logo_app.png